### ISSUE TITLE
Module 3 exercises [Prosper Detornu]

### ISSUE THREAD

**Issue by Prosper-Detornu** [SERVIR-WA/GALUP#129]
[Prosper Detornu Mod3_Execise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/6903479/Prosper.Detornu.Mod3_Execise.2.pdf)
[Model 3.pdf](https://github.com/SERVIR-WA/GALUP/files/6903610/Model.3.pdf)
[Prosper Detornu Mod3_Execise 1.pdf](https://github.com/SERVIR-WA/GALUP/files/6903611/Prosper.Detornu.Mod3_Execise.1.pdf)
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Ebenezer. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. There was an issue with the background map not showing up on your submissions, but this can be fixed by adding the map layer to your pdf. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
