### ISSUE TITLE
Module 3 exercises [Nada Tandoh]

### ISSUE THREAD

**Issue by Nadat1968** [SERVIR-WA/GALUP#135]
1. Please "drag & drop" exercise 1 pdf file below.
[Land Condition Map.pdf](https://github.com/SERVIR-WA/GALUP/files/6925532/Land.Condition.Map.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Market Suitability.pdf](https://github.com/SERVIR-WA/GALUP/files/6925535/Market.Suitability.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving

**Comment by JuliePeeling** [comment]
Well done, Nada. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. There was an issue with the background map not showing up on the market suitability submission, but this can be fixed by adding the map layer to your pdf. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
