### ISSUE TITLE
Module 1 exercises Sanoussi Manzo Maman Laminou

### ISSUE THREAD

**Issue by SanoussiMML** [SERVIR-WA/GALUP#137]
1. Please "drag & drop" exercise 1 pdf file below.
[Ghana population by district in 2018.pdf](https://github.com/SERVIR-WA/GALUP/files/6932547/Ghana.population.by.district.in.2018.pdf)
2. Please "drag & drop" exercise 2 pdf file below.
[Ghana population density by district in 2018.pdf](https://github.com/SERVIR-WA/GALUP/files/6932550/Ghana.population.density.by.district.in.2018.pdf)
3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Sanoussi. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. There was an issue with the color-bar used in your exercise 2 submission, but this can be fixed by matching the color-bar used in the sample pdf from Module 1. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
