### ISSUE TITLE
Module 1 exercises [Ama A Boadu]

### ISSUE THREAD

**Issue by Amaluspa** [SERVIR-WA/GALUP#21]
[Assignment 1. Ama.pdf](https://github.com/SERVIR-WA/GALUP/files/6609295/Assignment.1.Ama.pdf)
[Assignment 2. Ama.pdf](https://github.com/SERVIR-WA/GALUP/files/6609298/Assignment.2.Ama.pdf)

1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Ama. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. There was a minor issue with the labelling of the legend, but this can be fixed by adjusting the top text to describe what the legend is for instead of the name of the dataset. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.

**Comment by Amaluspa** [comment]
[Assignment 2 Corrections. Ama.pdf](https://github.com/SERVIR-WA/GALUP/files/6647711/Assignment.2.Corrections.Ama.pdf)
[Assignment 1 Corrections. Ama.pdf](https://github.com/SERVIR-WA/GALUP/files/6647714/Assignment.1.Corrections.Ama.pdf)

Hi. Kindly find attached my corrections for assignement 1 and 2 for module 1.

**Comment by JuliePeeling** [comment]
Looks perfect, thank you Ama!
