### ISSUE TITLE
Module 1 exercises [Nada N. Tandoh]

### ISSUE THREAD

**Issue by Nadat1968** [SERVIR-WA/GALUP#23]
1. Please "drag & drop" exercise 1 pdf file below.
[Ghana Population by Districts_Nada Tandoh.pdf](https://github.com/SERVIR-WA/GALUP/files/6609976/Ghana.Population.by.Districts_Nada.Tandoh.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Ghana Population Density by District_Nada Tandoh.pdf](https://github.com/SERVIR-WA/GALUP/files/6609978/Ghana.Population.Density.by.District_Nada.Tandoh.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Nada. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. There was a minor issue the coloring on exercise 1, but this can be fixed by ensuring that the correct "reds" color ramp is chosen so that the resulting map resembles the example in the module. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
