### ISSUE TITLE
Module 1 exercises [Judith N. Dery]

### ISSUE THREAD

**Issue by Jnommo** [SERVIR-WA/GALUP#59]
[Galup 1 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6651624/Galup.1.Judith.pdf)
[Galup 2 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6651627/Galup.2.Judith.pdf)

1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Judith. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. There was a minor issue with the labelling of the legend, but this can be fixed by adjusting the top text to describe what the legend is for instead of the name of the dataset. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.

**Comment by Jnommo** [comment]
Okay, thanks for the feedback
 The post module survey is asking for time taken to complete complete
midule 2, which we are yet to do, so I intend to fill it after the
training, is that okay?

**Comment by JuliePeeling** [comment]
Hi Judith,

The survey linked through Module 1 should not have any questions about Module 2, so that should be currently accessible. Please feel free to wait on the Module 2 post-survey until you have completed those exercises. Thank you!

**Comment by chjch** [comment]
Hi Judith,

Julie is right. You may have the wrong link. The Module 1 survey does not have any questions related to Module 2. Here is the link to it [https://ufl.qualtrics.com/jfe/form/SV_3n21W1ko0UPJNLo](https://ufl.qualtrics.com/jfe/form/SV_3n21W1ko0UPJNLo)

**Comment by Jnommo** [comment]
Thanks, I'll check it out.
