### ISSUE TITLE
Module 1 exercises [Francisca Ameley Armah -CERSGIS]

### ISSUE THREAD

**Issue by ameley1** [SERVIR-WA/GALUP#81]
[Uploading Population
[Population Map(Francisca Ameley Armah_CERSGIS).pdf](https://github.com/SERVIR-WA/GALUP/files/6763922/Population.Map.Francisca.Ameley.Armah_CERSGIS.pdf)
 Density (Francisca Ameley Armah_CERSGIS).pdf…]()
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.
[Population Density (Francisca Ameley Armah_CERSGIS).pdf](https://github.com/SERVIR-WA/GALUP/files/6763930/Population.Density.Francisca.Ameley.Armah_CERSGIS.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Hi Francisca, there seems to be an issue with Exercise 1, but it can be fixed by choosing the correct rendering field. It seems that you used “Area_km2” for the map symbology, while the correct field is “Pop_2018”. Otherwise, your Exercise 2 looks great! Please resubmit once the edits have been made, and we thank you for your participation. Please also be sure to fill out the module 1 survey if you have not already done so.

**Comment by ameley1** [comment]
Hello, Please find the corrected map for exercise 1. Thanks.
[Ghana Population Map(Francisca Ameley Armah_CERSGIS).pdf](https://github.com/SERVIR-WA/GALUP/files/6812153/Ghana.Population.Map.Francisca.Ameley.Armah_CERSGIS.pdf)

**Comment by JuliePeeling** [comment]
Looks perfect, thank you Francisca! Great work.
